### ISSUE TITLE
Error: Cannot find module 'hubot-mock-adapter'

### ISSUE THREAD

**Issue by emilsoman** [Hermanya/mock-hubot#1]
Trying to run the following Jasmine test after `npm install --save-dev mock-hubot` :

``` coffee
bot = require 'mock-hubot'
script = require '../src/script.coffee'

describe 'testing', ->
  beforeEach ->
    bot.start ->
      bot.learn script

  it 'passes', ->
    expect(true).toBe(true)
```

I'm getting the following error : 

```
Started
[Wed Sep 09 2015 23:33:31 GMT+0700 (WIB)] ERROR Cannot load adapter mock-adapter - Error: Cannot find module 'hubot-mock-adapter'
```

Any idea what's wrong ? I think I'm missing something simple, but I'm not sure what.

**Comment by Hermanya** [comment]
I'm not sure either. I tried to recreate this case, but it worked fine for me.
I'm running node v0.12.7 (try upgrading).

```
bot = require 'mock-hubot'
describe 'testing', ->
    beforeEach ->
        bot.start ->
            bot.learn (robot) ->
                console.log 'learned'
                robot.hear /hello/, (msg) ->
                    msg.send 'hello back'
    it 'passes', ->
        expect(true).toBe(true)
```

and run it with `jasmine-node --coffee testSpec.coffee`

**Comment by emilsoman** [comment]
Strange. @Hermanya can you please push a repo with the passing test ? Maybe then I can see if I'm doing something wrong.

**Comment by Hermanya** [comment]
https://github.com/Hermanya/mock-hubot-sample here @emilsoman

**Comment by emilsoman** [comment]
I had `hubot` under devDependencies in my package.json. I removed that (keeping hubot under peerDependencies), removed `node_modules`, `npm install` again and now it works. The package.json from your above repo helped me fix this. Thank you :) 

UPDATE: Keeping hubot under peerDependencies is still a problem. Here's a package.json that didn't work : 

```
  "peerDependencies": {
    "hubot": "2.x"
  },
  "devDependencies": {
    "jasmine": "^2.3.2",
    "mock-hubot": "^1.0.6"
  }
```

Here's what worked:

```
  "devDependencies": {
    "jasmine": "^2.3.2",
    "mock-hubot": "^1.0.6"
  }
```
